<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>final</name>
  <version>0.0.0</version>
  <description>High-level integration package for autonomous bot</description>
  <maintainer email="everygreen@todo.todo">everygreen</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>gazebo</exec_depend>
  <exec_depend>nav2</exec_depend>
  <exec_depend>waypoint</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
